# Site settings
title: Paspagon
email: contact@paspagon.com
description: >
  Sell your cloud-stored files for cryptocurrencies.
  No registration is needed and your customers may be anonymous.
baseurl: ""
url: "http://paspagon.com"

diaspora_profile_url: https://diasp.org/people/be3015f02dca0134b2c0782bcb452bd5
twitter_username: Paspagon
github_username:  Paspagon
subreddit: Paspagon
facebook_page: Paspagon
bitcointalk_thread_url: https://bitcointalk.org/index.php?topic=1362364.0

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  hard_wrap: true
  input: GFM

timezone: UTC
permalink: /blog/:categories/:year/:month/:day/:title/
