# Site settings
title: Paspagon
email: contact@paspagon.com
description: >
  Sell your cloud-stored files for cryptocurrencies.
  No registration is needed and your customers may be anonymous.
baseurl: ""
url: "http://paspagon.com"
twitter_username: Paspagon
github_username:  Paspagon
subreddit: Paspagon

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  hard_wrap: true
  input: GFM

timezone: UTC
permalink: /blog/:categories/:year/:month/:day/:title/
